"""Socle de vendeurs Discogs orientés musique électronique (Europe).

Compilé par recherche web (disquaires, labels, distributeurs, webshops), un
identifiant vendeur Discogs par entrée. Non vérifié : le job `scan_catalog`
teste chaque compte via l'API et retire les 404.

Amorce `/data/shared/sellers_catalog.json` au premier lancement ; ensuite le
fichier fait foi (l'utilisateur peut ajouter / désactiver des vendeurs).
"""

# u = username Discogs · c = pays · city · f = focus · t = type
SEED = [
    # --- Allemagne
    {"u": "hardwax-berlin", "name": "Hard Wax", "c": "DE", "city": "Berlin", "f": "techno/dub/house/dubstep", "t": "shop"},
    {"u": "spacehall.de", "name": "Spacehall", "c": "DE", "city": "Berlin", "f": "techno/house/minimal", "t": "shop"},
    {"u": "OyeRecordStore", "name": "OYE Records", "c": "DE", "city": "Berlin", "f": "house/disco/electronic 12\"", "t": "shop"},
    {"u": "Sound-Metaphors-shop", "name": "Sound Metaphors", "c": "DE", "city": "Berlin", "f": "disco/house/techno/reissue", "t": "shop"},
    {"u": "Bikini-Waxx-Records", "name": "Bikini Waxx", "c": "DE", "city": "Berlin", "f": "house/techno/electro", "t": "shop"},
    {"u": "rotation-boutique.de", "name": "Rotation Boutique", "c": "DE", "city": "Berlin", "f": "house/techno/ambient", "t": "shop"},
    {"u": "recordstore-berlin", "name": "The Record Store Berlin", "c": "DE", "city": "Berlin", "f": "soul/funk + dance", "t": "shop"},
    {"u": "www.hhv.de", "name": "HHV.de", "c": "DE", "city": "Berlin", "f": "electronic/hip hop/disco", "t": "webshop"},
    {"u": "recordsale-de", "name": "recordsale", "c": "DE", "city": "Berlin", "f": "2nd hand large stock", "t": "webshop"},
    {"u": "deejay.de.", "name": "Deejay.de", "c": "DE", "city": "Berlin", "f": "house/techno/minimal", "t": "webshop"},
    {"u": "Kompakt", "name": "Kompakt (mail-order)", "c": "DE", "city": "Cologne", "f": "techno/minimal/ambient", "t": "distributor"},
    {"u": "Kompakt.Plattenladen", "name": "Kompakt (shop)", "c": "DE", "city": "Cologne", "f": "techno/minimal/ambient", "t": "shop"},
    {"u": "grooveattackstore", "name": "Groove Attack", "c": "DE", "city": "Cologne", "f": "hip hop/house/techno/disco", "t": "shop"},
    {"u": "a-musik", "name": "a-Musik", "c": "DE", "city": "Cologne", "f": "experimental/electronic/leftfield", "t": "shop"},
    {"u": "Otaku_Records", "name": "Otaku Records", "c": "DE", "city": "Hamburg", "f": "techno/house/electro/dnb", "t": "shop"},
    {"u": "ZARDOZ-RECORDS", "name": "Zardoz Records", "c": "DE", "city": "Hamburg", "f": "2nd hand + electronic", "t": "shop"},
    {"u": "smallville_records", "name": "Smallville", "c": "DE", "city": "Hamburg", "f": "deep house/house/minimal", "t": "label"},
    {"u": "decks.de", "name": "Decks.de", "c": "DE", "city": "Wörrstadt", "f": "house/techno/electro/minimal", "t": "webshop"},
    {"u": "optimal-records.de", "name": "Optimal Records", "c": "DE", "city": "Munich", "f": "techno/dance/electronic", "t": "shop"},
    {"u": "possession", "name": "Public Possession", "c": "DE", "city": "Munich", "f": "leftfield house/techno/disco", "t": "shop"},
    {"u": "runningback", "name": "Running Back", "c": "DE", "city": "Frankfurt", "f": "house/disco/techno", "t": "label"},
    {"u": "vinyl_delirium", "name": "vinyl_delirium", "c": "DE", "city": "", "f": "techno/house", "t": "webshop"},
    {"u": "Fatplastics", "name": "Fatplastics", "c": "DE", "city": "Jena", "f": "techno/minimal/deep house", "t": "shop"},
    # --- Autriche
    {"u": "substance16", "name": "Substance", "c": "AT", "city": "Vienna", "f": "techno/electronica/experimental", "t": "shop"},
    {"u": "alt-neu.shop", "name": "Teuchtler / Alt & Neu", "c": "AT", "city": "Vienna", "f": "2nd hand all", "t": "shop"},
    {"u": "Black-Monk", "name": "Black Monk", "c": "AT", "city": "Vienna", "f": "2nd hand / collector", "t": "shop"},
    {"u": "3345recordsVienna", "name": "3345 Records", "c": "AT", "city": "Vienna", "f": "electronic/disco/house", "t": "shop"},
    {"u": "recordshop-austria", "name": "recordshop-austria", "c": "AT", "city": "", "f": "electronic/dance", "t": "webshop"},
    {"u": "ApartmentAcht", "name": "Apartment Acht", "c": "AT", "city": "Vienna", "f": "broken beat/soul/house/hip-hop", "t": "shop"},
    # --- Suisse
    {"u": "plattfon_records", "name": "Plattfon", "c": "CH", "city": "Basel", "f": "bass/minimal/ambient/techno", "t": "shop"},
    {"u": "bpm.store", "name": "bpm.store", "c": "CH", "city": "Basel", "f": "house/techno", "t": "webshop"},
    {"u": "Bongo_Joe_Shop", "name": "Bongo Joe", "c": "CH", "city": "Geneva", "f": "leftfield/world/electronic", "t": "shop"},
    {"u": "HouseShop", "name": "HouseShop", "c": "CH", "city": "", "f": "house/deep house/tech house/minimal", "t": "webshop"},
    # --- Pays-Bas
    {"u": "RushHour", "name": "Rush Hour", "c": "NL", "city": "Amsterdam", "f": "house/techno/disco/afro", "t": "shop"},
    {"u": "clone.nl", "name": "Clone", "c": "NL", "city": "Rotterdam", "f": "electro/techno/house/experimental", "t": "shop"},
    {"u": "Red_Light_Records", "name": "Red Light Records", "c": "NL", "city": "Amsterdam", "f": "house/techno/disco/wave", "t": "shop"},
    {"u": "KillaCutz", "name": "KillaCutz", "c": "NL", "city": "Amsterdam", "f": "chicago house/detroit techno/dnb", "t": "shop"},
    {"u": "recordmania.nl", "name": "Record Mania", "c": "NL", "city": "Amsterdam", "f": "2nd hand + dance", "t": "shop"},
    {"u": "WaxwellRecords", "name": "Waxwell Records", "c": "NL", "city": "Amsterdam", "f": "disco/funk/soul/house", "t": "shop"},
    {"u": "ConcertoRecordstore", "name": "Concerto", "c": "NL", "city": "Amsterdam", "f": "all 2nd hand", "t": "shop"},
    {"u": "bordelloaparigi", "name": "Bordello A Parigi", "c": "NL", "city": "Amsterdam", "f": "italo/disco/wave/minimal/EBM", "t": "shop"},
    {"u": "zwartgoud", "name": "Zwart Goud", "c": "NL", "city": "Amsterdam", "f": "techno/house/wave/ambient", "t": "shop"},
    {"u": "offbeat__records", "name": "Offbeat Records", "c": "NL", "city": "Rotterdam", "f": "disco/house/techno/wave 2nd hand", "t": "shop"},
    {"u": "Triple_Vision", "name": "Triple Vision", "c": "NL", "city": "Rotterdam", "f": "techno/house", "t": "distributor"},
    {"u": "DePlaatboef", "name": "De Plaatboef", "c": "NL", "city": "Rotterdam", "f": "2nd hand all", "t": "shop"},
    {"u": "koffie-leute-record-store", "name": "Koffie Leute", "c": "NL", "city": "Utrecht", "f": "dutch electronic labels/indie", "t": "shop"},
    {"u": "plato-utrecht", "name": "Plato Utrecht", "c": "NL", "city": "Utrecht", "f": "new & 2nd hand all", "t": "shop"},
    {"u": "DelsinRecords", "name": "Delsin Records", "c": "NL", "city": "Amsterdam", "f": "techno/electro/IDM", "t": "label"},
    {"u": "Dekmantel", "name": "Dekmantel", "c": "NL", "city": "Amsterdam", "f": "house/techno/leftfield", "t": "label"},
    # --- Belgique
    {"u": "dr.vinyl.", "name": "Doctor Vinyl", "c": "BE", "city": "Brussels", "f": "techno/house/acid/new beat/electro", "t": "shop"},
    {"u": "Crevette_Records", "name": "Crevette Records", "c": "BE", "city": "Brussels", "f": "dance/wave/disco/ambient/italo", "t": "shop"},
    {"u": "Veals_Geeks_Brussels", "name": "Veals & Geeks", "c": "BE", "city": "Brussels", "f": "psych + electronic/soundtracks", "t": "shop"},
    {"u": "wgwstore", "name": "Wally's Groove World", "c": "BE", "city": "Antwerp", "f": "house/techno/electro/disco/wave", "t": "shop"},
    {"u": "musicmanrecords", "name": "Music Man Records", "c": "BE", "city": "Ghent", "f": "techno/house", "t": "label"},
    {"u": "ConSouling", "name": "Consouling Sounds", "c": "BE", "city": "Ghent", "f": "doom/drone/ambient/experimental", "t": "label"},
    {"u": "Wool-E_Shop", "name": "Wool-E Discs", "c": "BE", "city": "Ghent", "f": "EBM/coldwave/minimal wave/electro", "t": "webshop"},
    # --- Royaume-Uni
    {"u": "PhonicaRecords", "name": "Phonica Records", "c": "UK", "city": "London", "f": "house/techno/disco/leftfield", "t": "shop"},
    {"u": "KristinaRecords", "name": "Kristina Records", "c": "UK", "city": "London", "f": "house/techno/minimal/synth", "t": "shop"},
    {"u": "Palace-Vinyl", "name": "Palace Vinyl", "c": "UK", "city": "London", "f": "house/techno/minimal", "t": "shop"},
    {"u": "waxmaterial", "name": "Wax Material", "c": "UK", "city": "London", "f": "minimal/micro-house/techno", "t": "webshop"},
    {"u": "Juno_Records", "name": "Juno Records", "c": "UK", "city": "London", "f": "house/techno/dnb/all dance", "t": "webshop"},
    {"u": "Honest_Jons", "name": "Honest Jon's", "c": "UK", "city": "London", "f": "dub/leftfield/house/techno/jazz", "t": "shop"},
    {"u": "Ryewax", "name": "Rye Wax", "c": "UK", "city": "London", "f": "house/techno/electro", "t": "shop"},
    {"u": "Lovevinylondon", "name": "Love Vinyl", "c": "UK", "city": "London", "f": "disco/house/techno", "t": "shop"},
    {"u": "Vinyl.Pimp.London", "name": "Vinyl Pimp", "c": "UK", "city": "London", "f": "house/techno/electro/general", "t": "webshop"},
    {"u": "eldica", "name": "Eldica", "c": "UK", "city": "London", "f": "reggae/funk/disco/leftfield/jazz", "t": "shop"},
    {"u": "lowcompany", "name": "Low Company", "c": "UK", "city": "London", "f": "EBM/industrial/leftfield/techno", "t": "label"},
    {"u": "SoundsOfTheUniverse", "name": "Sounds of the Universe", "c": "UK", "city": "London", "f": "disco/house/techno/dub/jazz", "t": "shop"},
    {"u": "sister_ray_london", "name": "Sister Ray", "c": "UK", "city": "London", "f": "general + electronic/experimental", "t": "shop"},
    {"u": "flashbacklondon", "name": "Flashback Records", "c": "UK", "city": "London", "f": "general 2nd hand + electronic", "t": "shop"},
    {"u": "Music.Shop.London", "name": "Music Shop London", "c": "UK", "city": "London", "f": "general + electronic", "t": "webshop"},
    {"u": "kudosrecords.co.uk", "name": "Kudos Records", "c": "UK", "city": "London", "f": "electronic/ambient/leftfield", "t": "distributor"},
    {"u": "Idle_Hands_Bristol", "name": "Idle Hands", "c": "UK", "city": "Bristol", "f": "dubstep/techno/house/bass/ambient", "t": "shop"},
    {"u": "easternbloc1985", "name": "Eastern Bloc", "c": "UK", "city": "Manchester", "f": "house/techno/dubstep/dnb", "t": "shop"},
    {"u": "Piccadillyrecords", "name": "Piccadilly Records", "c": "UK", "city": "Manchester", "f": "general + house/techno", "t": "shop"},
    {"u": "vinylexchange.co.uk", "name": "Vinyl Exchange", "c": "UK", "city": "Manchester", "f": "2nd hand general + electronic", "t": "shop"},
    {"u": "Kingbeerecords", "name": "King Bee Records", "c": "UK", "city": "Manchester", "f": "2nd hand soul/funk/disco/electronic", "t": "shop"},
    {"u": "rubadub", "name": "Rubadub", "c": "UK", "city": "Glasgow", "f": "techno/house/electro/bass/jungle", "t": "shop"},
    {"u": "Monorail", "name": "Monorail Music", "c": "UK", "city": "Glasgow", "f": "independent + electronic/leftfield", "t": "shop"},
    {"u": "undergroundsolushn", "name": "Underground Solu'shn", "c": "UK", "city": "Edinburgh", "f": "house/techno/dance", "t": "shop"},
    {"u": "TribeUK", "name": "Tribe Records", "c": "UK", "city": "Leeds", "f": "house/techno/electro/dub/dnb/disco", "t": "shop"},
    {"u": "CrashRecords", "name": "Crash Records", "c": "UK", "city": "Leeds", "f": "general + dance/electronic", "t": "shop"},
    {"u": "rarekindrecords", "name": "Rarekind Records", "c": "UK", "city": "Brighton", "f": "hip-hop/funk/soul/downtempo/dubstep", "t": "shop"},
    {"u": "unearthed-sounds", "name": "Unearthed Sounds", "c": "UK", "city": "Ryde", "f": "electronic/dubstep/ambient/leftfield", "t": "webshop"},
    {"u": "kellysrecords", "name": "Kelly's Records", "c": "UK", "city": "Cardiff", "f": "huge 2nd hand + electronic", "t": "shop"},
    {"u": "diversevinyl", "name": "Diverse Vinyl", "c": "UK", "city": "Newport", "f": "general + electronic", "t": "shop"},
    # --- Irlande
    {"u": "SpindizzyRecords", "name": "Spindizzy Records", "c": "IE", "city": "Dublin", "f": "techno/electro/breaks/house/dnb/IDM", "t": "shop"},
    {"u": "allcitydublin", "name": "All City Records", "c": "IE", "city": "Dublin", "f": "hip-hop/electronic/house/techno", "t": "shop"},
    {"u": "theragedublin", "name": "The R.A.G.E.", "c": "IE", "city": "Dublin", "f": "2nd hand general + electronic", "t": "shop"},
    # --- Nordiques
    {"u": "Fade-records", "name": "Fade Records", "c": "SE", "city": "Stockholm", "f": "techno/minimal/house/dnb/dub", "t": "shop"},
    {"u": "snickarsrecords", "name": "Snickars Records", "c": "SE", "city": "Stockholm", "f": "soul/funk/disco/techno/house/jazz", "t": "shop"},
    {"u": "petsoundsrecords", "name": "Pet Sounds Records", "c": "SE", "city": "Stockholm", "f": "general + electronic/leftfield", "t": "shop"},
    {"u": "OmegaRecordStockholm", "name": "Omega Records", "c": "SE", "city": "Stockholm", "f": "2nd hand + electronic", "t": "shop"},
    {"u": "recordmania.se", "name": "Record Mania (SE)", "c": "SE", "city": "Stockholm", "f": "2nd hand rarities + electronic", "t": "shop"},
    {"u": "recordhuntersweden", "name": "Record Hunter", "c": "SE", "city": "Stockholm", "f": "2nd hand general + electronic", "t": "shop"},
    {"u": "SkivhallenMajorna", "name": "Skivhallen", "c": "SE", "city": "Gothenburg", "f": "techno/house + 2nd hand", "t": "shop"},
    {"u": "bolero.recordstore", "name": "Bolero Record Store", "c": "SE", "city": "Malmö", "f": "underground/experimental/techno/tapes", "t": "shop"},
    {"u": "filtermusikk.no", "name": "Filter Musikk", "c": "NO", "city": "Oslo", "f": "techno/house/electro/acid", "t": "shop"},
    {"u": "dorma.21", "name": "Dorma 21", "c": "DK", "city": "Copenhagen", "f": "techno/minimal/house/electronic", "t": "shop"},
    {"u": "r66-copenhagen", "name": "Route 66", "c": "DK", "city": "Copenhagen", "f": "indie + general 2nd hand", "t": "shop"},
    {"u": "CopenhagenVinyl.eu", "name": "Copenhagen Vinyl", "c": "DK", "city": "Copenhagen", "f": "electronic/collector", "t": "webshop"},
    {"u": "Vinyl.Denmark", "name": "Vinyl.Denmark", "c": "DK", "city": "Copenhagen", "f": "general + electronic", "t": "webshop"},
    {"u": "Dis-Records", "name": "Dis Records", "c": "FI", "city": "Helsinki", "f": "techno/IDM/leftfield/electro/breaks", "t": "shop"},
    {"u": "redhillrecords", "name": "Redhill Records", "c": "FI", "city": "Helsinki", "f": "electronic/DJ 2nd hand", "t": "shop"},
    {"u": "recordshopx", "name": "Levykauppa Äx", "c": "FI", "city": "Helsinki", "f": "general + electronic", "t": "shop"},
    {"u": "digeliushelsinki", "name": "Digelius Music", "c": "FI", "city": "Helsinki", "f": "jazz/world/avant-garde/leftfield", "t": "shop"},
    {"u": "LuckyRecordsRvk", "name": "Lucky Records", "c": "IS", "city": "Reykjavik", "f": "funk/disco/electronic + icelandic", "t": "shop"},
    {"u": "reykjavikrecordshop", "name": "Reykjavík Record Shop", "c": "IS", "city": "Reykjavik", "f": "general 2nd + new", "t": "shop"},
    # --- France
    {"u": "Syncrophone-Stock", "name": "Syncrophone", "c": "FR", "city": "Paris", "f": "house/techno/disco/ambient", "t": "shop"},
    {"u": "Toolboxrecords", "name": "Toolbox Records", "c": "FR", "city": "Paris", "f": "hardcore/hard techno/breakcore/dnb", "t": "shop"},
    {"u": "yoyaku", "name": "Yoyaku", "c": "FR", "city": "Paris", "f": "minimal/micro-house/deep house/techno", "t": "webshop"},
    {"u": "dddrecordsparis", "name": "DDD Records", "c": "FR", "city": "Paris", "f": "techno/house/disco/bass/dnb", "t": "shop"},
    {"u": "BetinosRecordShop", "name": "Bétino's Record Shop", "c": "FR", "city": "Paris", "f": "disco/rare house/soul/funk/afro", "t": "shop"},
    {"u": "Kako_Records_Store", "name": "Kako Records Store", "c": "FR", "city": "Marseille", "f": "all + electronic", "t": "shop"},
    {"u": "extendandplay", "name": "Extend & Play", "c": "FR", "city": "Marseille", "f": "disco/rave/techno/house", "t": "shop"},
    {"u": "besides-records", "name": "Besides Records", "c": "FR", "city": "Lille", "f": "new & 2nd hand vinyl + electronic", "t": "shop"},
    {"u": "unite-centrale", "name": "Unité Centrale", "c": "FR", "city": "Lyon", "f": "techno/house/electro 12\"", "t": "shop"},
    {"u": "Willgroove", "name": "Willgroove", "c": "FR", "city": "", "f": "house/tech house/electro 12\"", "t": "webshop"},
    {"u": "EuropeVinylRecords", "name": "Breizh Tek Shop", "c": "FR", "city": "Rennes", "f": "techno/minimal/electro", "t": "webshop"},
    {"u": "identitydiffusion", "name": "Identity Diffusion", "c": "FR", "city": "Seine-Saint-Denis", "f": "techno/electro 12\"", "t": "shop"},
    {"u": "MusicHouseParis", "name": "Music House Paris", "c": "FR", "city": "Paris", "f": "house/techno 12\"", "t": "shop"},
    {"u": "dizonord.marseille", "name": "Dizonord", "c": "FR", "city": "Marseille", "f": "généraliste + electronic (occasion)", "t": "shop"},
    # --- Italie
    {"u": "serendeepity", "name": "Serendeepity", "c": "IT", "city": "Milan", "f": "techno/house/disco/bass/experimental", "t": "shop"},
    {"u": "totalrecords", "name": "Ultrasuoni Records", "c": "IT", "city": "Rome", "f": "techno/house/ambient/electro/wave/italo", "t": "shop"},
    {"u": "pink_moon_records", "name": "Pink Moon", "c": "IT", "city": "Rome", "f": "eclectic + electronic/disco", "t": "shop"},
    {"u": "semm", "name": "Semm Music Store", "c": "IT", "city": "Bologna", "f": "eclectic + electronic", "t": "shop"},
    # --- Espagne
    {"u": "discosparadiso", "name": "Discos Paradiso", "c": "ES", "city": "Barcelona", "f": "house/techno/electronic + reissue", "t": "shop"},
    {"u": "SubwaxBcn", "name": "Subwax BCN", "c": "ES", "city": "Barcelona", "f": "techno/acid/minimal/electro/house/ambient", "t": "shop"},
    {"u": "NUT_RECORDS", "name": "NUT Records", "c": "ES", "city": "Barcelona", "f": "house/techno/disco", "t": "shop"},
    {"u": "fari", "name": "Vinilarium", "c": "ES", "city": "Barcelona", "f": "house/techno/electro/acid/breaks 2nd hand", "t": "shop"},
    {"u": "WOIAJO", "name": "Barcelona City Records", "c": "ES", "city": "Barcelona", "f": "house/techno/electro/IDM/dnb/italo 2nd hand", "t": "shop"},
    {"u": "rotordiscos", "name": "Rotor Discos", "c": "ES", "city": "Madrid", "f": "industrial/experimental/ambient/IDM/techno/electro", "t": "shop"},
    {"u": "elalmacen", "name": "El Almacén de Discos", "c": "ES", "city": "Madrid", "f": "electronica/techno/house/wave/electro", "t": "shop"},
    {"u": "RadialStore", "name": "Radial Store", "c": "ES", "city": "Madrid", "f": "ambient/experimental/deep house/techno/jazz", "t": "shop"},
    {"u": "TotemTanz", "name": "TotemTanz", "c": "ES", "city": "Seville", "f": "all + electronic/breakbeat/house/dnb", "t": "shop"},
    {"u": "ARGONMENDIVALENCIA", "name": "Digital Records (Argon Mendi)", "c": "ES", "city": "Valencia", "f": "all + electronic", "t": "shop"},
    {"u": "Palco", "name": "Palco", "c": "ES", "city": "Alicante", "f": "house/deep house/tech house", "t": "webshop"},
    # --- Portugal
    {"u": "carpetandsnares", "name": "Carpet & Snares", "c": "PT", "city": "Lisbon", "f": "house/techno/electronic/ambient/experimental", "t": "shop"},
    {"u": "FlurDiscos", "name": "Flur Discos", "c": "PT", "city": "Lisbon", "f": "electronica/experimental/techno/house/disco", "t": "shop"},
    {"u": "MateriaPrima", "name": "Matéria Prima", "c": "PT", "city": "Porto", "f": "electronica/leftfield/drone/noise", "t": "shop"},
    {"u": "CircusRecordShop", "name": "Circus Records", "c": "PT", "city": "Porto", "f": "house/techno + eclectic", "t": "shop"},
    {"u": "BonesRecords", "name": "Bones Records", "c": "PT", "city": "Lisbon", "f": "deep house/house classics", "t": "webshop"},
    # --- Grèce
    {"u": "Homcore-Athens", "name": "Homcore", "c": "GR", "city": "Athens", "f": "electro/house/experimental/minimal/techno", "t": "shop"},
    {"u": "recordhazeathens", "name": "Geheimnis / RecordHaze", "c": "GR", "city": "Athens", "f": "wave/synth/electronic", "t": "webshop"},
    {"u": "harmonic", "name": "Vinyl Salvation", "c": "GR", "city": "Thessaloniki", "f": "house/techno/disco/edits/boogie/funk", "t": "shop"},
    # --- Europe de l'Est / centrale
    {"u": "SideOne", "name": "Side One", "c": "PL", "city": "Warsaw", "f": "house/nu-disco/minimal/tech-house/techno/electro", "t": "shop"},
    {"u": "polishculture.shop", "name": "Eudezet Records", "c": "PL", "city": "Łódź", "f": "house/techno (gros stock)", "t": "webshop"},
    {"u": "Acid-Works", "name": "Acid-Works", "c": "PL", "city": "", "f": "jungle/drum & bass", "t": "webshop"},
    {"u": "deeprecordstore", "name": "Deep", "c": "HU", "city": "Budapest", "f": "house/techno/dnb/dubstep/deep electronica", "t": "shop"},
    {"u": "Aktrecords_Budapest", "name": "Akt Records", "c": "HU", "city": "Budapest", "f": "techno/house/melodic techno", "t": "shop"},
    {"u": "MisBitsRecordSHop", "name": "Misbits Record Shop", "c": "RO", "city": "Bucharest", "f": "deep house/techno/dub techno/electro", "t": "shop"},
    {"u": "Pulz", "name": "Pulz", "c": "SI", "city": "Ljubljana", "f": "techno/house/minimal/electro/dub techno/UK garage/IDM", "t": "shop"},
    # --- Labels / distributeurs / rééditions
    {"u": "bewithrecords", "name": "Be With Records", "c": "UK", "city": "", "f": "boogie/AOR/balearic/library reissue", "t": "label"},
    {"u": "Livity-records", "name": "Livity Sound", "c": "UK", "city": "Bristol", "f": "UK techno/bass/dub", "t": "label"},
    {"u": "peacefrog", "name": "Peacefrog Records", "c": "UK", "city": "", "f": "house/techno/deep house", "t": "label"},
    {"u": "darkentriesrecords", "name": "Dark Entries", "c": "US", "city": "San Francisco", "f": "minimal wave/italo/EBM/electro reissue", "t": "label"},
]
